In [1]:
import torch

In [2]:
# Basic input [y = 2x + 1]
x = torch.tensor([[1.0], [2.0], [3.0], [4.0], [5.0]])
y = torch.tensor([[3.0], [5.0], [7.0], [9.0], [11.0]])

In [3]:
print(x)
print(y)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.]])
tensor([[ 3.],
        [ 5.],
        [ 7.],
        [ 9.],
        [11.]])


In [4]:
# Make basic linear model [y = mx + b] with random inputs
model = torch.nn.Linear(1, 1)

In [5]:
# Print random inputs [weight = m] [bias = b]; for [y = mx + b]
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.9870]], requires_grad=True)
Parameter containing:
tensor([0.1957], requires_grad=True)


In [6]:
# Prediction = x is put through the random model, then prints
prediction = model(x)

print(prediction)

tensor([[-0.7913],
        [-1.7783],
        [-2.7654],
        [-3.7524],
        [-4.7394]], grad_fn=<AddmmBackward0>)


In [7]:
# Creates a MSE loss object called loss_fn
loss_fn = torch.nn.MSELoss()

In [8]:
# Compares the prediction to the expected result, squares it then prints the average result
loss = loss_fn(prediction, y)
print(loss)

tensor(113.2073, grad_fn=<MseLossBackward0>)


In [9]:
# Resesets the gradiants starting clean
model.zero_grad()

In [10]:
# Start changing the gradiant using the loss
loss.backward()

In [11]:
# Prints gradiant
print("Weight gradient:", model.weight.grad)
print("Bias gradient:", model.bias.grad)

Weight gradient: tensor([[-70.5404]])
Bias gradient: tensor([-19.5307])


In [12]:
#Before one step
print("Before:")
print("Weight:", model.weight.item())
print("Bias:", model.bias.item())
print("Loss:", loss.item())

Before:
Weight: -0.9870351552963257
Bias: 0.1957331895828247
Loss: 113.2072525024414


In [13]:
#SGD = Stochastic Gradient Descent, one of the basic optimization algorithms.
#model.parameters() tells the optimizer which numbers it is allowed to change — in our case, the weight and bias.
#lr=0.01 sets the learning rate.

optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [14]:
#actually change the weights
optimizer.step()

In [15]:
#After one step
print("After:")
print("Weight:", model.weight.item())
print("Bias:", model.bias.item())

After:
Weight: -0.2816314101219177
Bias: 0.3910406231880188


In [16]:
#Print loss and prediction
prediction = model(x)
new_loss = loss_fn(prediction, y)

print("New prediction:")
print(prediction)

print("New loss:")
print(new_loss)

New prediction:
tensor([[ 0.1094],
        [-0.1722],
        [-0.4539],
        [-0.7355],
        [-1.0171]], grad_fn=<AddmmBackward0>)
New loss:
tensor(65.9716, grad_fn=<MseLossBackward0>)


In [17]:
#Main repeating line 

#for 100 lines
for epoch in range(100):
    #what it thinks y should be
    prediction = model(x)
    #finds (y-prediction)^2
    loss = loss_fn(prediction, y)
    #Resets gradiants simmilarly to model.zero_grad() but differnt for different models
    optimizer.zero_grad()
    #Calculate new gradiants
    loss.backward()
    #Use the gradiants to change the model using the optimize
    optimizer.step()

    #every 10 print loss
    if epoch % 10 == 0:
        print(epoch, loss.item())

0 65.97161865234375
10 0.29805490374565125
20 0.0014185367617756128
30 7.395482680294663e-05
40 6.345593283185735e-05
50 5.9276033425703645e-05
60 5.53923673578538e-05
70 5.1766150136245415e-05
80 4.8377220082329586e-05
90 4.520824950304814e-05


In [18]:
#Print Weight and Bias
print("Weight:", model.weight.item())
print("Bias:", model.bias.item())

Weight: 1.995780110359192
Bias: 1.0152350664138794


In [19]:
#Print what it thinks 10 would be
new_x = torch.tensor([[10.0]])
new_prediction = model(new_x)

print("Input:", new_x.item())
print("Prediction:", new_prediction.item())

Input: 10.0
Prediction: 20.973037719726562
