In [51]:
import torch

x = torch.tensor([[-3.0],
                  [-2.0],
                  [-1.0],
                  [ 0.0],
                  [ 1.0],
                  [ 2.0],
                  [ 3.0]])
y = x ** 2

model = torch.nn.Sequential(
    torch.nn.Linear(1,8),
    torch.nn.ReLU(),
    # 8 times does: hiddenLayer1 = (h1×weight[0]) + (h2×weight[1]) + (h3×weight[2]) + (⋯) + (h8×weight[7]) + bias;
    torch.nn.Linear(8,8),
    torch.nn.ReLU(),
    torch.nn.Linear(8,1)
)

loss_fn = torch.nn.MSELoss()

optimizer = torch.optim.SGD(model.parameters(), lr = 0.0001)

In [52]:
for epoch in range(100000):

    prediction = model(x)

    loss = loss_fn(prediction, y)

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

    if epoch % 1000 == 0:
        print("Epoch:", epoch, "Loss:", loss.item())

Epoch: 0 Loss: 25.599878311157227
Epoch: 1000 Loss: 4.20077657699585
Epoch: 2000 Loss: 2.0813138484954834
Epoch: 3000 Loss: 1.3988274335861206
Epoch: 4000 Loss: 0.9767223596572876
Epoch: 5000 Loss: 0.7147687673568726
Epoch: 6000 Loss: 0.5513526797294617
Epoch: 7000 Loss: 0.43903660774230957
Epoch: 8000 Loss: 0.36195823550224304
Epoch: 9000 Loss: 0.3086049556732178
Epoch: 10000 Loss: 0.2709965407848358
Epoch: 11000 Loss: 0.24392728507518768
Epoch: 12000 Loss: 0.22406218945980072
Epoch: 13000 Loss: 0.20920975506305695
Epoch: 14000 Loss: 0.19735416769981384
Epoch: 15000 Loss: 0.18756093084812164
Epoch: 16000 Loss: 0.17930521070957184
Epoch: 17000 Loss: 0.17223618924617767
Epoch: 18000 Loss: 0.16609346866607666
Epoch: 19000 Loss: 0.16068430244922638
Epoch: 20000 Loss: 0.15585768222808838
Epoch: 21000 Loss: 0.15149681270122528
Epoch: 22000 Loss: 0.14750869572162628
Epoch: 23000 Loss: 0.14381751418113708
Epoch: 24000 Loss: 0.14036621153354645
Epoch: 25000 Loss: 0.13710328936576843
Epoch: 260

In [53]:
test_x = torch.tensor([[-2.5],
                       [-1.5],
                       [-0.5],
                       [ 0.5],
                       [ 1.5],
                       [ 2.5]])

test_prediction = model(test_x)

print("Input:")
print(test_x)

print("\nAI prediction:")
print(test_prediction.detach())

print("\nActual x²:")
print(test_x ** 2)

Input:
tensor([[-2.5000],
        [-1.5000],
        [-0.5000],
        [ 0.5000],
        [ 1.5000],
        [ 2.5000]])

AI prediction:
tensor([[6.6242],
        [2.6167],
        [0.0750],
        [0.0782],
        [2.5391],
        [6.5570]])

Actual x²:
tensor([[6.2500],
        [2.2500],
        [0.2500],
        [0.2500],
        [2.2500],
        [6.2500]])


In [55]:
print("Final loss:", loss.item())

for name, parameter in model.named_parameters():
    print(name)
    print(parameter.detach())
    print()

Final loss: 0.061529796570539474
0.weight
tensor([[-0.6160],
        [ 0.1982],
        [ 0.4576],
        [ 0.5694],
        [ 1.4362],
        [-0.0206],
        [-1.2811],
        [-0.0116]])

0.bias
tensor([-0.5492, -0.5946, -0.3513, -1.1388, -0.7003,  1.0489, -0.6872, -0.6664])

2.weight
tensor([[ 0.0264,  0.3191, -0.1857,  0.1309, -0.1701, -0.2241, -0.2066, -0.3243],
        [-0.0039, -0.3273, -0.2812, -0.2884, -0.1846,  0.1558, -0.2089,  0.2552],
        [ 0.4667, -0.0998,  0.3895,  0.7042,  0.7683, -0.3672,  1.0390,  0.1502],
        [-0.0710,  0.1363, -0.1201, -0.0372, -0.3196, -0.3155,  0.1037,  0.0816],
        [ 0.4927,  0.0116,  0.1720,  0.6418,  0.5608,  0.0582,  0.7633, -0.3040],
        [-0.1623,  0.2023,  0.2554,  0.1810,  0.2625, -0.4801,  0.4611,  0.1637],
        [ 0.2966, -0.1938, -0.2072, -0.2313,  0.2367,  0.0218, -0.0114, -0.1608],
        [-0.3418, -0.2652, -0.0343, -0.1704,  0.4658,  0.1338, -0.1647,  0.0569]])

2.bias
tensor([ 0.3606, -0.0605,  0.0612,  0.041

In [56]:
test_x = torch.tensor([[2.0]])

layer1 = model[0](test_x)
relu1 = model[1](layer1)

layer2 = model[2](relu1)
relu2 = model[3](layer2)

output = model[4](relu2)

print("Layer 1:")
print(layer1)

print("\nAfter ReLU 1:")
print(relu1)

print("\nLayer 2:")
print(layer2)

print("\nAfter ReLU 2:")
print(relu2)

print("\nFinal prediction:")
print(output)

Layer 1:
tensor([[-1.7811e+00, -1.9822e-01,  5.6392e-01,  2.6345e-05,  2.1721e+00,
          1.0077e+00, -3.2494e+00, -6.8954e-01]], grad_fn=<AddmmBackward0>)

After ReLU 1:
tensor([[0.0000e+00, 0.0000e+00, 5.6392e-01, 2.6345e-05, 2.1721e+00, 1.0077e+00,
         0.0000e+00, 0.0000e+00]], grad_fn=<ReluBackward0>)

Layer 2:
tensor([[-3.3951e-01, -4.6314e-01,  1.5795e+00, -1.0386e+00,  1.0024e+00,
         -1.1280e-05,  3.9651e-01,  1.5235e+00]], grad_fn=<AddmmBackward0>)

After ReLU 2:
tensor([[0.0000, 0.0000, 1.5795, 0.0000, 1.0024, 0.0000, 0.3965, 1.5235]],
       grad_fn=<ReluBackward0>)

Final prediction:
tensor([[4.2030]], grad_fn=<AddmmBackward0>)
